import Head from "next/head";
import Body from "../components/Body";
import Header from "../components/Header";
import SmallCard from "../components/SmallCard";
import { useRouter } from "next/router";
import { useEffect, useState } from "react";
export default function Home({ exploreData }) {
  let router = useRouter();
  const [propState, setPropState] = useState(false);
  const [wildfires, setWildfires] = useState({});
  const [data1, setData1] = useState(null);
  const [data2, setData2] = useState(null);
  const [print, setPrint] = useState(false);

  useEffect(() => {
    let token = sessionStorage.getItem("Token");
    if (!token) {
      setPropState(false);
    }

    if (token) {
      setPropState(true);
      router.push("/");
    }
  }, []);

  console.log(exploreData);

  function getData1(val) {
    setPrint(false);
    setData1(val.target.value);
  }

  function getData2(val) {
    setPrint(false);
    setData2(val.target.value);
  }

  function sendProps() {
    router.push({
      pathname: "/footerAgain",
      query: { data1, data2 },
    })
  }

  return (
    <div className="">
      <Head>
        <title>wildfire-detector</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <Header props={propState} />
      <Body />
      <main className="max-w-7xl mx-auto px-8 sm:px-16">
        <section className="pt-6">
          <h4 className="text-2xl font-semibold pb-5">
            Enter your location by Co-ordinates to know if you are safe or not
          </h4>
          
          <input
            type="text"
            onChange={getData1}
            className="border-2 mb-3 mr-2 p-2 rounded-md"
            placeholder="longitude"
          />
          <input
            type="text"
            onChange={getData2}
            className="border-2 mb-3 mr-2 p-2 rounded-md"
            placeholder="latitude"
          />
          <button
            onClick={() => sendProps()}
            className="border-2 p-1 rounded-lg bg-gray-400 text-white hover:scale-105"
          >
            submit
          </button>
          <a className="sticky left-0 ml-[20%] text-blue-800 hover:underline hover:text-blue-900" href="https://www.gps-coordinates.net/gps-coordinates-converter" target="_blank">
            click this to find out your co-ordinates through your address
          </a>
          <h1 className="mb-3 text-gray-400">please wait for a few seconds after pressing the submit button while we fetch the data</h1>
        </section>
      </main>
    </div>
  );
}
